gcc main.c strtok_r.c xoshiro256plusplus.c m_raytriangleintersection.c m_vector.c f_objparser.c -o ../bin/gamelinux.exe -lm -g3 -O1 -Wall -std=c99 -Wno-missing-braces -I ../include/ -L ../lib/ -lraylinux -llua -lfluidsynth -lpcg_random

